### find all blogs
GET localhost:8080/api/v1/blogs

### find blogs with litmit
GET localhost:8080/api/v1/blogs/filter?limit=8

### find blog by id
GET localhost:8080/api/v1/blogs/2

### find blogs by categoryId
GET localhost:8080/api/v1/blogs/search?categoryId=1
