###Find reviews of detail by id
GET http://localhost:8080/api/v1/product-detail/1/reviews

###Find average rating of product by id
GET http://localhost:8080/api/v1/product-detail/1/reviews/average-rating

###Filter review by rating
GET localhost:8080/api/v1/product-detail/1/reviews/filter?rating=2

###Add review to product detail
POST http://localhost:8080/api/v1/product-detail/1/reviews
Content-Type: application/json

{
  "userId": 1,
  "productId": 1,
  "rating": 5,
  "text": "Very good"
}

###Update review to product detail
PUT http://localhost:8080/api/v1/product-detail/1/reviews/1
Content-Type: application/json

{
  "reviewId": 1,
  "userId": 1,
  "productId": 1,
  "rating": 5,
  "text": "Not very good"
}
