###Find All User
GET http://localhost:8080/api/v1/users
###Find User By Id
GET http://localhost:8080/api/v1/users/1

###Change User password By Id
PUT http://localhost:8080/api/v1/users/1/change-password
Content-Type: application/json

{
  "currentPassword": "123456",
  "newPassword": "123"
}
###Update User info By Id
PUT http://localhost:8080/api/v1/users/1
Content-Type: application/json

{
  "fullName": "Tui ten moi",
  "phone": "092323683"
}
###Find order list of user
GET http://localhost:8080/api/v1/users/1/orders

###Find address list of user
GET http://localhost:8080/api/v1/users/1/address

###User Register
POST localhost:8080/api/v1/users/register
Content-Type: application/json

{
  "email": "dubanteo2003@gmail.com",
  "password": "12345623",
  "fullName": "Du Thi Teo"
}
###User Login
POST localhost:8080/api/v1/users/login
Content-Type: application/json

{
  "email": "minh@gmail.com",
  "password": "123456"
}

###Forgot password
POST http://localhost:8080/api/v1/users/forgot-password
Content-Type: application/json

{
  "email": "dubanteo2003@gmail.com"
}